meta_title: "EventR | Facilitez vos fêtes entre amis"
meta_description: "Un anniv ? Une soirée BBQ ? Pas de panique, EventR vous aide à organiser la fête pour savoir qui ramène quoi."
meta_image: "bg-1200x630.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@RevancheSites"